<% secrets = YAML.load_file('./secrets/secrets.yml')[ENV['RAILS_ENV'] || "development"] %>
defaults: &defaults
  cloud_crowd_server:   http://sourceafrica.net:8080
  server_root:          sourceafrica.net
  large_file_storage:   /mnt/large_files
  aws_region:           us-east-1
  aws_zone:             us-east-1c
  preconfigured_ami_id: <%= secrets['ami'] %>
  asset_root:           "sourceafrica.net"

development:
  <<: *defaults

staging:
  <<: *defaults
  cloud_crowd_server: <%= secrets['db_host'] %>:8080
  server_root:        staging.sourceafrica.net
  asset_root:         "s3.amazonaws.com/dcloud_staging"

production:
  <<: *defaults
  cloud_crowd_server: <%= secrets['db_host'] %>:8080
  server_root:        sourceafrica.net
<<<<<<< HEAD
  asset_root:         "sourceafrica.net"
  db_volume_id:       vol-d4c305bd
=======
  asset_root:         "s3-eu-west-1.amazonaws.com/s3.sourceafrica.net"
  db_volume_id:       vol-3248332d
>>>>>>> 55689e3838b9432ae0b6134514829d8d7627c674

test:
  <<: *defaults
