<% secrets = YAML.load_file('./secrets/secrets.yml')[ENV['RAILS_ENV'] || "development"] %>
defaults: &defaults
  cloud_crowd_server:   http://52.16.133.220:8080
  server_root:          ec2-52-16-133-220.eu-west-1.compute.amazonaws.com
  large_file_storage:   /mnt/large_files
  aws_region:           us-east-1
  aws_zone:             us-east-1b
  preconfigured_ami_id: <%= secrets['ami'] %>
  asset_root:           s3-us-east-1.amazonaws.com/dcloud-cfafrica

development:
  <<: *defaults

staging:
  <<: *defaults
  cloud_crowd_server: <%= secrets['db_host'] %>:8080
  server_root:        staging.sourceafrica.net
  asset_root:         s3.amazonaws.com/dcloud_staging

production:
  <<: *defaults
  cloud_crowd_server: <%= secrets['db_host'] %>:8080
  server_root:        ec2-52-16-133-220.eu-west-1.compute.amazonaws.com
  asset_root:         s3-us-east-1.amazonaws.com/dcloud-cfafrica
  db_volume_id:       vol-d4c305bd

test:
  <<: *defaults
