<% secrets = YAML.load_file('./secrets/secrets.yml')[ENV['RAILS_ENV'] || "development"] %>
production:
  solr:
    hostname: <%= secrets['solr_host'] %>
    port: 7377
    path: /solr/collection1
    read_timeout: 5
    open_timeout: 1.5
    log_level: INFO
    min_memory: 1G
    max_memory: 2G
    pid_dir: tmp/pids

development:
  solr:
    hostname: localhost
    port: 7377
    log_level: ALL
    path: /solr/collection1
    pid_dir: tmp/pids

test:
  solr:
    hostname: localhost
    port: 8982
    log_level: WARNING
    path: /solr/collection1
    pid_dir: tmp/pids

staging:
  solr:
    hostname: ip-172-31-0-170.eu-west-1.compute.internal
    port: 7377
    log_level: WARNING
    pid_dir: tmp/pids
    path: /solr/collection1
