production:
  solr:
    hostname: ec2-52-16-133-220.eu-west-1.compute.amazonaws.com
    port: 7377
    path: /solr/collection1
    read_timeout: 5
    open_timeout: 1.5
    log_level: INFO
    min_memory: 1G
    max_memory: 2G
    pid_dir: tmp/pids
    solr_home: solr

development:
  solr:
    hostname: ec2-52-16-133-220.eu-west-1.compute.amazonaws.com
    port: 7377
    log_level: ALL
    path: /solr/collection1
    pid_dir: tmp/pids

test:
  solr:
    hostname: localhost
    port: 8982
    log_level: WARNING
    path: /solr/collection1
    pid_dir: tmp/pids

staging:
  solr:
    hostname: ec2-52-16-133-220.eu-west-1.compute.amazonaws.com
    port: 7377
    log_level: WARNING
    pid_dir: tmp/pids
    path: /solr/collection1
